export const ACTIONS = {
    NOTIFICATION: 'NOTIFICATION',
    AUTHENTICATED: 'AUTHENTICATED',
    ADD_CART: 'ADD_CART',
    ADD_MODAL: 'ADD_MODAL',
    ADD_ORDERS: 'ADD_ORDERS',
    ADD_USERS: 'ADD_USERS',
    ADD_CATEGORIES: 'ADD_CATEGORIES',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
}